name: 'Build: Javascript Sample'

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*
      - hotfix/*
    paths:
      - 'javascript-sample/**'

  pull_request:
    branches:
      - main

    paths:
      - 'javascript-sample/**'

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./javascript-sample
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./javascript-sample/package-lock.json
          node-version: '20.x'
          cache: 'npm'

      - name: Install NPM packages
        run: npm install

      - name: Generate with Astronuts
        run: npx astronuts-generate

      - name: Run Astronuts Code Quality Checks
        uses: astronuts-app/astronuts-code-quality-action@v5
        with:
          rootDir: ./javascript-sample
