name: 'Build: Java Sample'

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*
      - hotfix/*
    paths:
      - 'java-sample/**'

  pull_request:
    branches:
      - main

    paths:
      - 'java-sample/**'

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java-sample
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean build --console=plain --scan

      - name: Run Astronuts Code Quality Checks
        uses: astronuts-app/astronuts-code-quality-action@v4
        with:
          sourceLanguage: 'java'
          buildSystem: 'gradle'
          rootDir: ./java-sample
