name: 'Build: Python Sample'

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*
      - hotfix/*
    paths:
      - 'python-sample/**'

  pull_request:
    branches:
      - main
    paths:
      - 'python-sample/**'

jobs:
  Build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./python-sample

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyclean
          pip install -r requirements.txt
          pyclean .
          astronuts-generate

      - name: Run Astronuts Code Quality Checks
        uses: astronuts-app/astronuts-code-quality-action@v4
        with:
          rootDir: ./python-sample